name: website

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws-region: us-east-2
      - name: Sync files to S3 bucket
        run: |
         aws s3 sync build ./ s3://mydivinebucket29/
